### ISSUE TITLE
FC with linux-6.0: vmstat_refresh: nr_file_hugepages -44 

### ISSUE THREAD

**Issue by ol-sergeyn** [Xilinx-CNS/onload#130] opened 2023-03-09 09:57 UTC
There are kernel warnings sometimes when running Onload on Fedora with Linux 6.0:
`vmstat_refresh: nr_file_hugepages -44`.

It can be reproduced with socket tester:
`--tester-run=sockapi-ts/attacks/ethernet/oversized*2 --ool=onload`

Note: the warnings do not appear with NDEBUG onload build.

I've bisected Linux:
```
793917d997df2e432f3e9ac126e4482d68256d01 is the first bad commit
commit 793917d997df2e432f3e9ac126e4482d68256d01
Author: Matthew Wilcox (Oracle) <willy@infradead.org>
Date:   Wed Feb 5 11:27:01 2020 -0500

    mm/readahead: Add large folio readahead

    Allocate large folios in the readahead code when the filesystem supports
    them and it seems worth doing.  The heuristic for choosing which folio
    sizes will surely need some tuning, but this aggressive ramp-up has been
    good for testing.

    Signed-off-by: Matthew Wilcox (Oracle) <willy@infradead.org>

 mm/readahead.c | 106 +++++++++++++++++++++++++++++++++++++++++++++++++++++----
 1 file changed, 99 insertions(+), 7 deletions(-)
```
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=793917d997df2e432f3e9ac126e4482d68256d01

**Comment by ol-sergeyn** [comment] 2023-03-21 12:33
Still reproducible with `master`54958ab612

**Comment by ivatet-amd** [comment] 2023-03-21 13:56
Thanks for checking this, @ol-sergeyn.

**Comment by ivatet-amd** [comment] 2023-12-05 14:39
@ol-sergeyn I wonder if it's still an issue after merging https://github.com/Xilinx-CNS/onload/pull/138 where we refactored the huge page allocator in the kernel?

**Comment by okt-sergeyn** [comment] 2023-12-08 14:55
I can't reproduce the issue anymore on current master [569aec1](https://github.com/Xilinx-CNS/onload/commit/569aec1c20363139e047b4a773dd2fcf0d4f6e59)
My setup is Fedora 38 with `6.5.6-200.fc38.x86_64`.

Feel free to close it.

**Closed** 2023-12-08 15:28 UTC
